lint:
  files_exist:
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/awstest.yml
    - CODE_OF_CONDUCT.md
    - assets/multiqc_config.yml
    - assets/nf-core-certificate_logo_light.png
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/modules.config
    - conf/test_full.config
    - docs/images/nf-core-certificate_logo_dark.png
    - docs/images/nf-core-certificate_logo_light.png
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - CODE_OF_CONDUCT.md
    - assets/email_template.txt
    - assets/nf-core-certificate_logo_light.png
    - assets/sendmail_template.txt
    - docs/README.md
    - docs/images/nf-core-certificate_logo_dark.png
    - docs/images/nf-core-certificate_logo_light.png
  multiqc_config: false
  modules_config: false
  nf_test_content: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: maxulysse
  description: generate pdf certificates
  force: false
  is_nfcore: false
  name: certificate
  org: maxulysse
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 1.0.0dev
